<a href="https://colab.research.google.com/github/kashish-kannojia/UCS420-KASHISHKANNOJIA/blob/main/Assignment5_cognitive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# ASSIGNMENT5


# Q.1 Write a program to create a NumPy 1D-array with 5 elements and
# perform basic operations like:


num_arr=np.array([1,2,3,4,5])


# a) Addition of 2 in all the element
print("Adding 2 to all th elements",num_arr+2)


# b) Multiply 3 with all the elements
print("Multiplying 3 to all the elements",num_arr*3)


# c) Divide every element by 2
print("Dividing every element by 2",num_arr/2)

Adding 2 to all th elements [3 4 5 6 7]
Multiplying 3 to all the elements [ 3  6  9 12 15]
Dividing every element by 2 [0.5 1.  1.5 2.  2.5]


In [11]:
# Q.2 Questions on Basic NumPy Array:
# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

arr=np.array([1,2,3,4,5])

reverse_arr=arr[::-1]

print(reverse_arr)


# b) Find the most frequent value and their indice(s) in the following
# arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1])

x=np.array([1,2,3,4,5,1,2,1,1,1])

count=0
max_count=0
most_frequent=0

for i in x:
  for element in x:
    if element==i:
      count=count+1
  if count>max_count:
    max_count=count
    most_frequent=i

indices=[]
for i in range(len(x)):
  if x[i]==most_frequent:
    indices.append(i);

print("The most_frequent value is" , most_frequent)
print("Its indices are", indices)



# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
y=np.array([1,1,1,2,3,4,2,4,3,3])


count1=0
max_count1=0
most_frequent1=0

for j in y:
  for element in y:
    if element==j:
      count1=count1+1
  if count1>max_count1:
    max_count1=count1
    most_frequent1=j

indices1=[]
for i in range(len(y)):
  if y[i]==most_frequent1:
    indices1.append(i);

print("The most_frequent value is" , most_frequent1)
print("Its indices are", indices1)

[5 4 3 2 1]
The most_frequent value is 1
Its indices are [0, 5, 7, 8, 9]
The most_frequent value is 3
Its indices are [4, 8, 9]


In [16]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]),
# access elements using row and column indices as follows:
# a) Access 1st row, 2nd column

arr_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])

print("1st row,2nd column",arr_2d[0,1])



# b) Access 3rd row, 1st column
print("3rd row,1st column",arr_2d[2,0])


1st row,2nd column 20
3rd row,1st column 70


In [24]:
# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with
# evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions
# of the array, shape, total elements, the data type of each element and total
# number of bytes consumed by the array. Find the transpose of this array using
# reshape() attribute. Can we do the same with T attribute?

Kashish=np.linspace(10,100,25)

print("Array:")

print(Kashish)

print("The dimension of the array is:", Kashish.ndim)

print("The shape of the array",Kashish.shape)

print("The total elements in the array",Kashish.size)

print("The data type of each element is:",Kashish.dtype)

print("The total number of bytes consumed by the array",Kashish.nbytes)

print("The transpose of the array using reshape:")
print(Kashish.reshape(1,25))


print("Transpose of the array using T")
print(Kashish.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
The dimension of the array is: 1
The shape of the array (25,)
The total elements in the array 25
The data type of each element is: float64
The total number of bytes consumed by the array 200
The transpose of the array using reshape:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose of the array using T
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [31]:
# Q5. Create a 2-D Array of three rows and four columns, named
# ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90,
# 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the
# array to four rows and three columns and name it as reshaped_ucs420_<your_name>>. Resize the array to two rows and three columns and
# name it as resized_ ucs420_<your_name>>.

ucs420_kashish=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])


print("The mean of the array is:")
print(np.mean(ucs420_kashish))


print("The meadian of the array is:")
print(np.median(ucs420_kashish))


print("The maximum value of the array is:")
print(np.max(ucs420_kashish))

print("The minimum value of the array is:")
print(np.min(ucs420_kashish))

print("The unique elements of the array are:")
print(np.unique(ucs420_kashish))

reshaped_ucs420_kashish=ucs420_kashish.reshape(4,3)

print("The reshaped array is:")
print(reshaped_ucs420_kashish)



resized_ucs420_kashish=np.resize(ucs420_kashish,(2,3))
print("The resize array is:")
print(resized_ucs420_kashish)



The mean of the array is:
43.333333333333336
The meadian of the array is:
37.5
The maximum value of the array is:
90
The minimum value of the array is:
10
The unique elements of the array are:
[10 15 20 30 35 40 50 60 70 80 90]
The reshaped array is:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
The resize array is:
[[10 20 30]
 [40 50 60]]
